# Generated by Django 4.1.5 on 2023-02-16 10:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='uploadpdf',
            old_name='fileupload',
            new_name='imageupload',
        ),
    ]
